// Builds a single .ttf icon font from the SVGs under ./svgs.
// Each icon gets a private-use Unicode codepoint starting at 0xE001.
// Emits both ../../resources/fonts/iconfont.ttf (consumed by CIQ) and
// ../../source/UI/IconFontCodes.mc.txt (reference table for the codes
// we just assigned — pasted into IconFont.mc by hand).

const fs = require('fs');
const path = require('path');
const { SVGIcons2SVGFontStream } = require('svgicons2svgfont');
const svg2ttf = require('svg2ttf');

const SVG_DIR = path.join(__dirname, 'svgs');
const OUT_SVG_FONT = path.join(__dirname, 'iconfont.svg');
const OUT_TTF = path.join(__dirname, '..', '..', 'resources', 'fonts', 'iconfont.ttf');
const OUT_CODES = path.join(__dirname, 'codes.txt');
const OUT_MC = path.join(__dirname, '..', '..', 'source', 'UI', 'IconFont.mc');

// Deterministic order so re-running keeps the codepoints stable.
const FILES = fs.readdirSync(SVG_DIR).filter(f => f.endsWith('.svg')).sort();

const fontStream = new SVGIcons2SVGFontStream({
    fontName: 'HyroxIcons',
    normalize: true,
    fontHeight: 1000,
    log: () => {},
});
const svgOut = fs.createWriteStream(OUT_SVG_FONT);
fontStream.pipe(svgOut);

let code = 0xE001;
const mapping = {};

for (const file of FILES) {
    const name = path.basename(file, '.svg');
    mapping[name] = code;
    const glyph = fs.createReadStream(path.join(SVG_DIR, file));
    glyph.metadata = {
        unicode: [String.fromCharCode(code)],
        name: name.replace(/-/g, '_'),
    };
    fontStream.write(glyph);
    code += 1;
}
fontStream.end();

svgOut.on('finish', () => {
    fs.mkdirSync(path.dirname(OUT_TTF), { recursive: true });
    const svgFont = fs.readFileSync(OUT_SVG_FONT, 'utf8');
    const ttf = svg2ttf(svgFont, {});
    fs.writeFileSync(OUT_TTF, Buffer.from(ttf.buffer));
    fs.unlinkSync(OUT_SVG_FONT);

    const lines = Object.entries(mapping).map(
        ([n, c]) => `${n.padEnd(18)} => 0x${c.toString(16).toUpperCase()}  (\\u{${c.toString(16)}})`
    );
    fs.writeFileSync(OUT_CODES, lines.join('\n') + '\n');

    // Emit IconFont.mc with explicit \uXXXX escapes so string literals are
    // byte-stable regardless of tooling that might strip private-use
    // Unicode glyphs. Regenerated on every build; do NOT hand-edit.
    const constLines = Object.entries(mapping).map(([name, code]) => {
        const constName = name.toUpperCase().replace(/-/g, '_');
        const hex = code.toString(16).toUpperCase().padStart(4, '0');
        return `    const ${constName.padEnd(14)} = "\\u${hex}";`;
    });
    const mc = [
        '//',
        '//  IconFont.mc',
        '//  HyroxSimGarmin',
        '//',
        '//  Created by bbdyno on 4/22/26.',
        '//',
        '',
        'import Toybox.Graphics;',
        'import Toybox.Lang;',
        'import Toybox.WatchUi;',
        '',
        '// AUTO-GENERATED by tools/iconfont/build.js — do not hand-edit.',
        '// Regenerate when SVGs are added/removed; codepoints are assigned',
        '// in alphabetic filename order.',
        '//',
        '// Attribution: Icons adapted from Lucide (https://lucide.dev), ISC license.',
        'module IconFont {',
        '',
        ...constLines,
        '',
        '    var _font = null;',
        '',
        '    function get() as FontResource {',
        '        if (_font == null) {',
        '            _font = WatchUi.loadResource(Rez.Fonts.iconfont) as FontResource;',
        '        }',
        '        return _font;',
        '    }',
        '}',
        '',
    ].join('\n');
    fs.writeFileSync(OUT_MC, mc);

    console.log('TTF:', OUT_TTF);
    console.log('MC :', OUT_MC);
    console.log('Codes:', OUT_CODES);
    console.log(lines.join('\n'));
});
